// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package message

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GetMessageClient is the client API for GetMessage service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GetMessageClient interface {
	Get(ctx context.Context, in *ARequest, opts ...grpc.CallOption) (*AResponse, error)
}

type getMessageClient struct {
	cc grpc.ClientConnInterface
}

func NewGetMessageClient(cc grpc.ClientConnInterface) GetMessageClient {
	return &getMessageClient{cc}
}

func (c *getMessageClient) Get(ctx context.Context, in *ARequest, opts ...grpc.CallOption) (*AResponse, error) {
	out := new(AResponse)
	err := c.cc.Invoke(ctx, "/message.GetMessage/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetMessageServer is the server API for GetMessage service.
// All implementations must embed UnimplementedGetMessageServer
// for forward compatibility
type GetMessageServer interface {
	Get(context.Context, *ARequest) (*AResponse, error)
	mustEmbedUnimplementedGetMessageServer()
}

// UnimplementedGetMessageServer must be embedded to have forward compatible implementations.
type UnimplementedGetMessageServer struct {
}

func (UnimplementedGetMessageServer) Get(context.Context, *ARequest) (*AResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedGetMessageServer) mustEmbedUnimplementedGetMessageServer() {}

// UnsafeGetMessageServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GetMessageServer will
// result in compilation errors.
type UnsafeGetMessageServer interface {
	mustEmbedUnimplementedGetMessageServer()
}

func RegisterGetMessageServer(s grpc.ServiceRegistrar, srv GetMessageServer) {
	s.RegisterService(&GetMessage_ServiceDesc, srv)
}

func _GetMessage_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ARequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GetMessageServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/message.GetMessage/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GetMessageServer).Get(ctx, req.(*ARequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GetMessage_ServiceDesc is the grpc.ServiceDesc for GetMessage service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GetMessage_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "message.GetMessage",
	HandlerType: (*GetMessageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _GetMessage_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/message.proto",
}
